apiVersion: apps/v1
kind: Deployment
metadata: 
  name: monitering-app
  labels:
    app: monitering_app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: monitering_app
  template:
    metadata:
      labels:
        app: monitering_app
    spec:
      containers:
      - name: monitering-app
        image: monitering-app:1.3
        ports:
        - containerPort: 5000